language: node_js

node_js:
  - "6.9.1"
  - "stable"

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database rms;' -U postgres

cache:
  directories:
    - node_modules

services:
  - postgresql

script:
  - npm run lint
  - npm test
  - npm run test-node